#!/usr/bin/env bash
#
# Native (no-Docker) installer for the Arpeggio OMR service on macOS.
# Intended for the Intel MacBook backend when Docker Desktop is too heavy.
#
# It installs JDK 25 + Tesseract via Homebrew, builds Audiveris 5.10.2 from
# source, and creates a Python virtualenv with the service dependencies.
#
# Idempotent-ish: re-running skips work that is already done.
#
set -euo pipefail

AUDIVERIS_REF="${AUDIVERIS_REF:-5.10.2}"
SERVICE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # services/omr
BUILD_DIR="${SERVICE_DIR}/.native"
AUDIVERIS_SRC="${BUILD_DIR}/audiveris"
VENV_DIR="${BUILD_DIR}/venv"

echo "==> Arpeggio OMR native install (Audiveris ${AUDIVERIS_REF})"
mkdir -p "${BUILD_DIR}"

# 1. Homebrew dependencies -----------------------------------------------------
if ! command -v brew >/dev/null 2>&1; then
  echo "ERROR: Homebrew not found. Install it from https://brew.sh first." >&2
  exit 1
fi

echo "==> Installing JDK 25 + Tesseract via Homebrew"
brew list openjdk@25 >/dev/null 2>&1 || brew install openjdk@25
brew list tesseract   >/dev/null 2>&1 || brew install tesseract
brew list python@3.12 >/dev/null 2>&1 || brew install python@3.12

# Locate the Homebrew JDK 25 (Apple Silicon vs Intel prefixes differ).
JAVA_HOME="$(brew --prefix openjdk@25)/libexec/openjdk.jdk/Contents/Home"
if [ ! -x "${JAVA_HOME}/bin/java" ]; then
  # Intel Homebrew lays it out slightly differently.
  JAVA_HOME="$(brew --prefix openjdk@25)"
fi
export JAVA_HOME
export PATH="${JAVA_HOME}/bin:${PATH}"
echo "==> JAVA_HOME=${JAVA_HOME}"
java -version

# Tesseract language data (Homebrew installs eng by default).
TESSDATA_PREFIX="$(brew --prefix tesseract)/share/tessdata"
export TESSDATA_PREFIX
echo "==> TESSDATA_PREFIX=${TESSDATA_PREFIX}"

# 2. Build Audiveris from source ----------------------------------------------
if [ ! -d "${AUDIVERIS_SRC}/.git" ]; then
  echo "==> Cloning Audiveris ${AUDIVERIS_REF}"
  git clone --depth 1 --branch "${AUDIVERIS_REF}" \
      https://github.com/Audiveris/audiveris.git "${AUDIVERIS_SRC}"
fi

echo "==> Building Audiveris (this can take several minutes)"
( cd "${AUDIVERIS_SRC}" && ./gradlew --no-daemon build -x test )

# Unpack the distribution tarball to a stable location.
tar -xf "${AUDIVERIS_SRC}"/app/build/distributions/app-*.tar -C "${BUILD_DIR}"
AUDIVERIS_LAUNCHER="$(ls -d "${BUILD_DIR}"/app-*/bin/Audiveris | head -1)"
echo "==> Audiveris launcher: ${AUDIVERIS_LAUNCHER}"

# 3. Python virtualenv ---------------------------------------------------------
echo "==> Creating Python virtualenv"
"$(brew --prefix python@3.12)/bin/python3.12" -m venv "${VENV_DIR}"
"${VENV_DIR}/bin/pip" install --upgrade pip
"${VENV_DIR}/bin/pip" install -r "${SERVICE_DIR}/requirements.txt"

# 4. Emit an env file that run-native.sh will source --------------------------
cat > "${BUILD_DIR}/env.sh" <<EOF
# Auto-generated by install-native.sh — sourced by run-native.sh
export JAVA_HOME="${JAVA_HOME}"
export PATH="${JAVA_HOME}/bin:\$PATH"
export TESSDATA_PREFIX="${TESSDATA_PREFIX}"
export AUDIVERIS_CMD="${AUDIVERIS_LAUNCHER}"
export AUDIVERIS_VERSION="${AUDIVERIS_REF}"
export VENV_DIR="${VENV_DIR}"
EOF

echo "==> Done. Start the service with: bash scripts/run-native.sh"
