#!/usr/bin/env bash
#
# Native installer WITHOUT Homebrew — for the old Intel MacBook backend running
# macOS 11 (Big Sur), where Homebrew is unsupported and the system Python (3.8)
# and JDK (17) are too old for this project.
#
# Everything is installed under ~/arpeggio (no sudo, nothing system-wide):
#   - Temurin JDK 21           (tarball from Adoptium)
#   - Python 3.12 + venv       (via `uv`, a single static binary)
#   - Tesseract `eng` data     (traineddata download; the native lib is bundled
#                               inside Audiveris via javacpp)
#   - Audiveris 5.10.2         (built from source with the JDK 21 above)
#
# Emits ~/arpeggio/omr/.native/env.sh, which run-native.sh sources to start up.
#
set -euo pipefail

AUDIVERIS_REF="${AUDIVERIS_REF:-5.10.2}"
# Audiveris 5.10.2 compiles at Java source release 25, so it needs JDK 25.
JDK_VERSION="${JDK_VERSION:-25}"
SERVICE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # services/omr
BASE="${HOME}/arpeggio"
BUILD_DIR="${SERVICE_DIR}/.native"
JDK_DIR="${BASE}/jdk${JDK_VERSION}"
TESSDATA_DIR="${BASE}/tessdata"
AUDIVERIS_SRC="${BASE}/audiveris-src"
AUDIVERIS_DIST="${BASE}/audiveris"
VENV_DIR="${BUILD_DIR}/venv"

mkdir -p "${BASE}" "${BUILD_DIR}"
echo "==> [1/6] Arpeggio native (no-Homebrew) install on $(sw_vers -productVersion)"

# 1. Temurin JDK 21 ----------------------------------------------------------
if [ ! -x "${JDK_DIR}/Contents/Home/bin/java" ]; then
  echo "==> [2/6] Downloading Temurin JDK ${JDK_VERSION} (x64)"
  mkdir -p "${JDK_DIR}"
  curl -fsSL -o "${BASE}/jdk.tar.gz" \
    "https://api.adoptium.net/v3/binary/latest/${JDK_VERSION}/ga/mac/x64/jdk/hotspot/normal/eclipse"
  tar -xzf "${BASE}/jdk.tar.gz" -C "${JDK_DIR}" --strip-components=1
  rm -f "${BASE}/jdk.tar.gz"
else
  echo "==> [2/6] JDK ${JDK_VERSION} already present"
fi
export JAVA_HOME="${JDK_DIR}/Contents/Home"
export PATH="${JAVA_HOME}/bin:${PATH}"
java -version

# 2. Tesseract language data -------------------------------------------------
if [ ! -f "${TESSDATA_DIR}/eng.traineddata" ]; then
  echo "==> [3/6] Downloading Tesseract eng.traineddata"
  mkdir -p "${TESSDATA_DIR}"
  curl -fsSL -o "${TESSDATA_DIR}/eng.traineddata" \
    "https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata"
else
  echo "==> [3/6] tessdata already present"
fi
export TESSDATA_PREFIX="${TESSDATA_DIR}"

# 3. Build Audiveris from source --------------------------------------------
# Skip the (multi-minute) build if a launcher is already present.
EXISTING_LAUNCHER="$(ls -d "${AUDIVERIS_DIST}"/app-*/bin/Audiveris 2>/dev/null | head -1 || true)"
if [ -x "${EXISTING_LAUNCHER:-/nonexistent}" ]; then
  echo "==> [4/6] Audiveris already built: ${EXISTING_LAUNCHER}"
  AUDIVERIS_LAUNCHER="${EXISTING_LAUNCHER}"
else
  if [ ! -d "${AUDIVERIS_SRC}/.git" ]; then
    echo "==> [4/6] Cloning Audiveris ${AUDIVERIS_REF}"
    git clone --depth 1 --branch "${AUDIVERIS_REF}" \
        https://github.com/Audiveris/audiveris.git "${AUDIVERIS_SRC}"
  fi
  echo "==> [4/6] Building Audiveris (several minutes)…"
  ( cd "${AUDIVERIS_SRC}" && ./gradlew --no-daemon --console=plain build -x test )
  mkdir -p "${AUDIVERIS_DIST}"
  tar -xf "${AUDIVERIS_SRC}"/app/build/distributions/app-*.tar -C "${AUDIVERIS_DIST}"
  AUDIVERIS_LAUNCHER="$(ls -d "${AUDIVERIS_DIST}"/app-*/bin/Audiveris | head -1)"
  echo "==> Audiveris launcher: ${AUDIVERIS_LAUNCHER}"
fi

# 4. Python 3.12 via uv ------------------------------------------------------
if ! command -v uv >/dev/null 2>&1 && [ ! -x "${HOME}/.local/bin/uv" ]; then
  echo "==> [5/6] Installing uv (userland Python manager)"
  curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="${HOME}/.local/bin:${PATH}"
echo "==> [5/6] Creating Python 3.12 venv"
uv python install 3.12
uv venv --clear --python 3.12 "${VENV_DIR}"
uv pip install --python "${VENV_DIR}/bin/python" -r "${SERVICE_DIR}/requirements.txt"

# 5. Emit env file for run-native.sh ----------------------------------------
echo "==> [6/6] Writing ${BUILD_DIR}/env.sh"
cat > "${BUILD_DIR}/env.sh" <<EOF
# Auto-generated by install-native-nobrew.sh — sourced by run-native.sh
export JAVA_HOME="${JAVA_HOME}"
export PATH="${JAVA_HOME}/bin:\$PATH"
export TESSDATA_PREFIX="${TESSDATA_PREFIX}"
export AUDIVERIS_CMD="${AUDIVERIS_LAUNCHER}"
export AUDIVERIS_VERSION="${AUDIVERIS_REF}"
export VENV_DIR="${VENV_DIR}"
# macOS 11's libc++ is too old for the bundled Tesseract native lib, so disable
# OCR: Audiveris still recognizes notes and exports MusicXML (text is skipped).
export OMR_DISABLE_OCR=true
EOF

echo "==> DONE. Start with: bash scripts/run-native.sh"
